# Generated by Django 3.2.14 on 2022-11-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_agenda_especialidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='codiogo',
            new_name='codigo',
        ),
        migrations.AlterField(
            model_name='especialidades',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
