# Generated by Django 3.2.14 on 2022-11-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_especialidades_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='fecha',
            new_name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='agenda',
            name='fecha_inicio',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
