# Generated by Django 3.2.14 on 2022-11-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20221119_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_fin',
            field=models.DateTimeField(default='2021-10-01'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_inicio',
            field=models.DateTimeField(default='2021-10-01'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hospital',
            field=models.CharField(choices=[('Hospital de Niños', 'Hospital de Niños'), ('Hospital de Niños de la Maternidad', 'Hospital de Niños de la Maternidad'), ('Hospital Pirovano', 'Hospital Pirovano'), ('Hospital Vicente López', 'Hospital Vicente López'), ('Hospital de Clínicas', 'Hospital de Clínicas'), ('Hospital de Clínicas de la Universidad de Buenos Aires', 'Hospital de Clínicas de la Universidad de Buenos Aires')], max_length=250),
        ),
    ]
