# Generated by Django 3.2.14 on 2022-11-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_auto_20221121_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='fecha_fin',
            field=models.DateTimeField(default='2021-10-11 10:00:00'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_inicio',
            field=models.DateTimeField(default='2021-10-10 10:00:00'),
        ),
    ]
