# Generated by Django 3.2.14 on 2022-11-21 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20221121_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='fecha_fin',
        ),
    ]
